### ISSUE TITLE
🐛 Bug Report - Mozambique digits

### ISSUE THREAD

**Issue by Elson-Timana** [ArtyomVancyan/antd-phone-input#42]
The number of Mozambique has in total of 9 digits after the prefix **258**, however, the `antd-phone-input` only accept 8 digits.

**Comment by ArtyomVancyan** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Mozambique), 8 and 9 are both valid length phone numbers for Mozambique, and only 8 is considered in [`validations.json`](https://github.com/ArtyomVancyan/antd-phone-input/blob/master/src/legacy/validations.json). Thank you, @Elson-Timana, for the report. This will be fixed in the next release

**Comment by Elson-Timana** [comment]
Thanks, but i cannot find this file in my project, as you can see in image below.

![image](https://github.com/ArtyomVancyan/antd-phone-input/assets/8736811/1d19b281-ccec-46f1-b6af-cbd78eed4c78)

**Comment by ArtyomVancyan** [comment]
It was not supposed to be in your project. The file is a part of the `antd-phone-input`, and you use it as a dependency.

**Comment by Elson-Timana** [comment]
Thanks, then how can i resolve this issue? it's important to my project because I'm from Mozambique

**Comment by ArtyomVancyan** [comment]
If you want to contribute, you can clone this repository, open the `src/legacy/validations.json`, and add another possible length to the `phoneNumber` property in the list. You should change the `mz` only. After you make the changes, you should build and install the local build to verify the validity. If all looks okay, open a pull request through GitHub and I will review it.

Or just wait for 1-2 days, I will fix this with upcoming optimizations and you will use the fresh release.

**Comment by Elson-Timana** [comment]
Sounds great, I think I can wait.
